### ISSUE TITLE
About the fine tune

### ISSUE THREAD

**Issue by luodezhao** [laura-wang/video_repres_mas#2]
Hi,Thanks for your sharing.

As you have mentioned in the paper, you retain the conv layers weights and fine tune the three fully-connected layers. Why didn't your fine tune  the whole network?

Thanks you.

**Comment by laura-wang** [comment]
@luodezhao , there may be some misunderstanding here.  During the experiment, we retrain the conv layer weights, and re-initialize the fc layer weights. But we finetune the whole network.
